name: IJF Automation

on:
  workflow_dispatch:
    inputs:
      spreadsheet:
        description: "スプレッドシート"
        required: true
        type: choice
        options:
          - MAN
          - WOMAN

  schedule:
    - cron: "0 */6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 gspread google-auth

      - name: Write credentials.json
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' > credentials.json

      - name: Select Spreadsheet
        run: |
          if [ "${{ github.event.inputs.spreadsheet }}" = "main" ]; then
            echo "SPREADSHEET_URL=${{ vars.SPREADSHEET_MAIN }}" >> $GITHUB_ENV
          else
            echo "SPREADSHEET_URL=${{ vars.SPREADSHEET_TEST }}" >> $GITHUB_ENV
          fi

      - name: Run script
        env:
          SHEET_NAME: ${{ vars.SHEET_NAME }}

          START_ROW: ${{ vars.START_ROW }}
          END_ROW: ${{ vars.END_ROW }}

          FULLNAME_COL: ${{ vars.FULLNAME_COL }}
          FAMILY_COL: ${{ vars.FAMILY_COL }}
          GIVEN_COL: ${{ vars.GIVEN_COL }}

          OUTPUT_COL: ${{ vars.OUTPUT_COL }}

        run: |
          python -u main.py
