name: IJF Search

on:

  workflow_dispatch:

    inputs:

      sheet:

        description: "Sheet"

        required: true

        type: choice

        options:

          - MAN

          - WOMAN

  schedule:

    - cron: "0 */6 * * *"


jobs:

  run:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v4


      - uses: actions/setup-python@v5

        with:

          python-version: "3.11"


      - name: install

        run: pip install -r requirements.txt


      - name: create credentials

        run: echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' > credentials.json


      - name: select sheet

        run: |

          if [ "${{ github.event.inputs.sheet }}" = "MAN" ]; then

            echo "SPREADSHEET_URL=https://docs.google.com/spreadsheets/d/1Fzgqgqv3zOKE36v7DCMp-z4JGSDHhVv0b5JEgjQmx5k" >> $GITHUB_ENV

          else

            echo "SPREADSHEET_URL=https://docs.google.com/spreadsheets/d/1SwjfDRfcikHrNo38CgFjwBa_oWQM5pnGynFeqikeVU4" >> $GITHUB_ENV

          fi


      - name: run script

        env:

          SHEET_NAME: Sheet1

          START_ROW: 2

          END_ROW: 1000

          FULLNAME_COL: K

          FAMILY_COL: I

          GIVEN_COL: J

          OUTPUT_COL: Q

        run: |

          python main.py
